/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
  developerTools:
  [
    'developer-tools/overview',        
        {
          "type": "category",
          "label": "WebOps",
          "collapsed": false,
          "items": [
            {
              "type": 'autogenerated',
              "dirName": 'developer-tools/webops'
            },
          ]
        }
      ],

  themeSidebar:
    [
      'faststore/overview',      
      {
        "type": "category",
        "label": "Getting Started",
        "collapsed": true,
        "items": [
          'faststore/tutorials/overview',          
          {
            "type": "category",
            "label": "Creating storefronts with Gatsby",
            "collapsed": true,
            "items": [
              'faststore/tutorials/gatsby/gatsby',
              "faststore/tutorials/gatsby/1",
              "faststore/tutorials/gatsby/2",
              "faststore/tutorials/gatsby/3",
              "faststore/tutorials/gatsby/4",
            ],
          },
        ],
      },
      {
        "type": "category",
        "label": "References",
        "collapsed": false,
        "items": [
          'faststore/reference/overview',
          {
            "type": "category",
            "label": "API",
            "collapsed": true,
            "items": [
              "faststore/reference/api/overview",
            ],
          },
          {
            "type": "category",
            "label": "SDK",
            "collapsed": true,
            "items": [
              "faststore/reference/api/overview",
            ],
          },
          {
            "type": "category",
            "label": "UI",
            "collapsed": true,
            "items": [
              "faststore/reference/api/overview",
            ],
          },
        ],
      },
      {
        "type": "category",
        "label": "How-to Guides",
        "collapsed": false,
        "items": [
          'faststore/how-to-guides/overview',
          'faststore/how-to-guides/migrating-from-SF',
          {
            "type": "category",
            "label": "Local development",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/development/development"
            ],
          },
          {
            "type": "category",
            "label": "Styling",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/styling/styling-components"
            ],
          },
          {
            "type": "category",
            "label": "Fetching data",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/fetching-data/fetching-data"
            ],
          },
          {
            "type": "category",
            "label": "Routing",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/routing/managing-url-redirects"
            ],
          },
          {
            "type": "category",
            "label": "Performance",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/performance/performance"
            ],
          },
          {
            "type": "category",
            "label": "Testing",
            "collapsed": true,
            "items": [
              "faststore/how-to-guides/testing/e2e-testing"
            ],
          },
        ],
      },
      {
        "type": "category",
        "label": "Conceptual Guides",
        "collapsed": true,
        "items": [
          'faststore/conceptual-guides/overview',
          'faststore/conceptual-guides/J-jamstack',
          'faststore/conceptual-guides/P-plugin',
          'faststore/conceptual-guides/S-shadowing',
          'faststore/conceptual-guides/S-starter',
          'faststore/conceptual-guides/S-ssg',
        ],
      },      
    ],
  
    shoppingSidebar:
    [
      'shopping-experiences/overview', 
    ],
    appsSidebar:
    [
      'apps/overview', 
    ],
    stackSidebar:
    [
      'stack/0', 
      'stack/1', 
      'stack/2', 
      'stack/3', 
    ]
};
